# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
  workflow_dispatch:
    inputs:
      observe:
        required: false
        default: false
        type: boolean

jobs:
  build_images:
    if: github.repository == 'crashoverride-poc/opentelemetry-demo'
    uses: ./.github/workflows/component-build-images.yml
