name: Build chalked image

on:
  workflow_dispatch:
    inputs:
      push:
        description: Should the images be pushed
        default: true
        required: false
        type: boolean
      version:
        description: The version used when tagging the image
        default: "dev"
        required: false
        type: string
      commit:
        description: Commit SHA or branch/tag to checkout (leave empty for default)
        default: ""
        required: false
        type: string
      branch:
        description: Branch to checkout (defaults to current branch)
        default: ""
        required: false
        type: string

jobs:
  protobufcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit || inputs.branch || github.ref }}
      - name: Generate
        run: make clean docker-generate-protobuf
      # - name: Check Clean Work Tree
      #   run: make check-clean-work-tree

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: protobufcheck

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"

    strategy:
      fail-fast: false
      matrix:
        file_tag:
          - file: ./src/accounting/Dockerfile
            tag_suffix: accounting
            context: ./
            setup-qemu: true
          - file: ./src/ad/Dockerfile
            tag_suffix: ad
            context: ./
            setup-qemu: true
          - file: ./src/cart/src/Dockerfile
            tag_suffix: cart
            context: ./
            setup-qemu: false
          - file: ./src/checkout/Dockerfile
            tag_suffix: checkout
            context: ./
            setup-qemu: true
          - file: ./src/currency/Dockerfile
            tag_suffix: currency
            context: ./
            setup-qemu: true
          - file: ./src/email/Dockerfile
            tag_suffix: email
            context: ./
            setup-qemu: true
          - file: ./src/fraud-detection/Dockerfile
            tag_suffix: fraud-detection
            context: ./
            setup-qemu: true
          - file: ./src/frontend/Dockerfile
            tag_suffix: frontend
            context: ./
            setup-qemu: true
          - file: ./src/frontend-proxy/Dockerfile
            tag_suffix: frontend-proxy
            context: ./
            setup-qemu: true
          - file: ./src/frontend/Dockerfile.cypress
            tag_suffix: frontend-tests
            context: ./
            setup-qemu: true
          - file: ./src/image-provider/Dockerfile
            tag_suffix: image-provider
            context: ./
            setup-qemu: true
          - file: ./src/kafka/Dockerfile
            tag_suffix: kafka
            context: ./
            setup-qemu: true
          - file: ./src/load-generator/Dockerfile
            tag_suffix: load-generator
            context: ./
            setup-qemu: true
          - file: ./src/payment/Dockerfile
            tag_suffix: payment
            context: ./
            setup-qemu: true
          - file: ./src/product-catalog/Dockerfile
            tag_suffix: product-catalog
            context: ./
            setup-qemu: true
          - file: ./src/quote/Dockerfile
            tag_suffix: quote
            context: ./
            setup-qemu: true
          - file: ./src/recommendation/Dockerfile
            tag_suffix: recommendation
            context: ./
            setup-qemu: true
          - file: ./src/shipping/Dockerfile
            tag_suffix: shipping
            context: ./
            setup-qemu: true
          - file: ./src/flagd-ui/Dockerfile
            tag_suffix: flagd-ui
            context: ./
            setup-qemu: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.commit || inputs.branch || github.ref }}

      - name: Setup Chalk
        uses: crashappsec/setup-chalk-action@main
        with:
          connect: true

      - name: Load environment variables from .env file
        run: |
          if [ -f .env ]; then
            # Filter out comments and empty lines, then add each variable to $GITHUB_ENV
            grep -vE '^\s*#|^\s*$' .env | while read -r line; do
              echo "$line" >> $GITHUB_ENV
            done
          else
            echo ".env file not found!"
            exit 1
          fi

      - name: Check for changes and set push options
        id: check_changes
        run: |
          DOCKERFILE_DIR=$(dirname ${{ matrix.file_tag.file }})

          # If a specific commit is provided, always build (no change detection)
          if [ -n "${{ inputs.commit }}" ]; then
            echo "Specific commit requested, proceeding with build."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          else
            # Original change detection logic
            FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- $DOCKERFILE_DIR)
            FORCE_PUSH=${{ inputs.push }}
            if [ "$FORCE_PUSH" = true ]; then
              echo "Force push is enabled, proceeding with build."
              echo "skip=false" >> "$GITHUB_OUTPUT"
            elif [ -z "$FILES_CHANGED" ]; then
              echo "No changes in ${{ matrix.file_tag.context }}, skipping build."
              echo "skip=true" >> "$GITHUB_OUTPUT"
            else
              echo "Changes detected in ${{ matrix.file_tag.context }}, proceeding with build."
              echo "skip=false" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: Assume AWS Role
        id: role
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 #v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubDeploy

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #   if: ${{ inputs.push }}
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #   if: ${{ inputs.push }}

      - name: Set up QEMU
        if: ${{ matrix.file_tag.setup-qemu }}
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
            max-parallelism = 2
      - name: Matrix Build and push demo images
        if: steps.check_changes.outputs.skip == 'false'
        uses: docker/build-push-action@v6.15.0
        with:
          context: ${{ matrix.file_tag.context }}
          file: ${{ matrix.file_tag.file }}
          platforms: linux/amd64
          push: ${{ inputs.push }}
          sbom: true
          provenance: true
          build-args: |
            OTEL_JAVA_AGENT_VERSION=${{ env.OTEL_JAVA_AGENT_VERSION }}
            OPENTELEMETRY_CPP_VERSION=${{ env.OPENTELEMETRY_CPP_VERSION }}
            TRACETEST_IMAGE_VERSION=${{ env.TRACETEST_IMAGE_VERSION }}
          tags: |
            ${{ secrets.AWS_ECR_PREFIX }}/demo/${{matrix.file_tag.tag_suffix }}:${{ inputs.version }}
            ${{ secrets.AWS_ECR_PREFIX }}/demo/${{matrix.file_tag.tag_suffix }}:latest
          # ${{ inputs.dockerhub_repo }}:${{ inputs.version }}-${{matrix.file_tag.tag_suffix }}
          # ${{ inputs.dockerhub_repo }}:latest-${{matrix.file_tag.tag_suffix }}
          # ${{ inputs.ghcr_repo }}:${{ inputs.version }}-${{ matrix.file_tag.tag_suffix }}
          # ${{ inputs.ghcr_repo }}:latest-${{ matrix.file_tag.tag_suffix }}
          cache-from: type=gha
          cache-to: type=gha
