name: Build chalked image

on:
  workflow_dispatch:
    inputs:
      push:
        description: Should the images be pushed
        default: true
        required: false
        type: boolean
      version:
        description: The version used when tagging the image
        default: "dev"
        required: false
        type: string
      commit:
        description: Commit SHA or branch/tag to checkout (leave empty for default)
        default: ""
        required: false
        type: string
      branch:
        description: Branch to checkout (defaults to current branch)
        default: ""
        required: false
        type: string

jobs:
  protobufcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit || inputs.branch || github.ref }}
      - name: Generate
        run: make docker-generate-protobuf
      # - name: Check Clean Work Tree
      #   run: make check-clean-work-tree

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: protobufcheck

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"

    strategy:
      fail-fast: false
      matrix:
        file_tag:
          - file: ./src/accounting/Dockerfile
            tag_suffix: accounting
            context: ./
            setup-qemu: true
          - file: ./src/ad/Dockerfile
            tag_suffix: ad
            context: ./
            setup-qemu: true
          - file: ./src/cart/src/Dockerfile
            tag_suffix: cart
            context: ./
            setup-qemu: false
          - file: ./src/checkout/Dockerfile
            tag_suffix: checkout
            context: ./
            setup-qemu: true
          - file: ./src/currency/Dockerfile
            tag_suffix: currency
            context: ./
            setup-qemu: true
          - file: ./src/email/Dockerfile
            tag_suffix: email
            context: ./
            setup-qemu: true
          - file: ./src/fraud-detection/Dockerfile
            tag_suffix: fraud-detection
            context: ./
            setup-qemu: true
          - file: ./src/frontend/Dockerfile
            tag_suffix: frontend
            context: ./
            setup-qemu: true
          - file: ./src/frontend-proxy/Dockerfile
            tag_suffix: frontend-proxy
            context: ./
            setup-qemu: true
          - file: ./src/frontend/Dockerfile.cypress
            tag_suffix: frontend-tests
            context: ./
            setup-qemu: true
          - file: ./src/image-provider/Dockerfile
            tag_suffix: image-provider
            context: ./
            setup-qemu: true
          - file: ./src/kafka/Dockerfile
            tag_suffix: kafka
            context: ./
            setup-qemu: true
          - file: ./src/load-generator/Dockerfile
            tag_suffix: load-generator
            context: ./
            setup-qemu: true
          - file: ./src/payment/Dockerfile
            tag_suffix: payment
            context: ./
            setup-qemu: true
          - file: ./src/product-catalog/Dockerfile
            tag_suffix: product-catalog
            context: ./
            setup-qemu: true
          - file: ./src/quote/Dockerfile
            tag_suffix: quote
            context: ./
            setup-qemu: true
          - file: ./src/recommendation/Dockerfile
            tag_suffix: recommendation
            context: ./
            setup-qemu: true
          - file: ./src/shipping/Dockerfile
            tag_suffix: shipping
            context: ./
            setup-qemu: true
          - file: ./src/flagd-ui/Dockerfile
            tag_suffix: flagd-ui
            context: ./
            setup-qemu: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.commit || inputs.branch || github.ref }}

      #      - name: Enable debug
      #        if: always()
      #        shell: bash
      #        run: |
      #          echo "CURIOSITY_STRACE=/mnt/curiosity/co-strace" >> $GITHUB_ENV

      - name: Setup Chalk
        uses: crashappsec/setup-chalk-action@main
        with:
          connect: true
          version: latest
          latest_version_url: https://dl.crashoverride.run/crashoverride/chalk/current-version.txt

      - name: Assume AWS Role
        id: role
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 #v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubDeploy

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Set up QEMU
        if: ${{ matrix.file_tag.setup-qemu }}
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
            max-parallelism = 2

      - name: Matrix Build and push demo images
        if: steps.check_changes.outputs.skip == 'false'
        uses: docker/build-push-action@v6.15.0
        with:
          context: ${{ matrix.file_tag.context }}
          file: ${{ matrix.file_tag.file }}
          platforms: linux/amd64
          push: ${{ inputs.push }}
          sbom: true
          provenance: true
          build-args: |
            OTEL_JAVA_AGENT_VERSION=${{ env.OTEL_JAVA_AGENT_VERSION }}
            OPENTELEMETRY_CPP_VERSION=${{ env.OPENTELEMETRY_CPP_VERSION }}
            TRACETEST_IMAGE_VERSION=${{ env.TRACETEST_IMAGE_VERSION }}
          tags: |
            ${{ secrets.AWS_ECR_PREFIX }}/demo/${{matrix.file_tag.tag_suffix }}:${{ inputs.version }}
            ${{ secrets.AWS_ECR_PREFIX }}/demo/${{matrix.file_tag.tag_suffix }}:latest
          cache-from: type=gha
          cache-to: type=gha

      - name: Check for crashes in the server
        if: always()
        shell: bash
        run: |
          ls /mnt/curiosity
          echo "Disabling monitoring"
          echo "LD_PRELOAD=" >> $GITHUB_ENV
          ls -hlia /mnt/curiosity/
          if [[ $(grep -c 'p 00000000' /mnt/curiosity/co-host.log) -gt 5 ]] \
            || [[ $(grep -E -c 'FATAL: Uncaught signal|Address not mapped at|RAX 0x.*RBX 0x' /mnt/curiosity/co-host.log) -gt 1 ]] \
            || ls /mnt/curiosity/coredump.* &> /dev/null; then
          echo "crash found. Failing the workflow."
          exit 1
          fi
          jq --slurp "." /mnt/curiosity/observables/* > /dev/null || exit 1
          if [ -f "/mnt/curiosity/runc.log" ] && grep -q 'E:' "/mnt/curiosity/runc.log"; then
            return 1
          fi || exit 0

      - name: Upload curiosity Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job }}-${{ github.run_id }}-${{ runner.arch }}-${{ matrix.file_tag.tag_suffix }}-observables-artifacts"
          path: |
            /mnt/curiosity/**
            !/mnt/curiosity/co-hook-entry.so
            !/mnt/curiosity/co-jq
            !/mnt/curiosity/co-strace
            !/mnt/curiosity/hostd.sock
            !/mnt/curiosity/coredump-handler.sh
            !/mnt/curiosity/docker-buildx.bkp
