name: Sync Fork

permissions:
  contents: write

on:
  schedule:
    # Run every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email "ci@crashoverride.com"
          git config --local user.name "ci"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/open-telemetry/opentelemetry-demo.git

      - name: Sync with Upstream
        run: |
          git fetch upstream
          git fetch origin
          git checkout upstream
          git rebase upstream/main

      - name: Push Changes
        run: |
          git push https://${{ secrets.CI_PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:upstream --force

      - name: Trigger Chalk and Push Workflow
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CI_PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/chalk-and-push.yml/dispatches \
            -d '{"ref":"main","inputs":{"push":"true","version":"dev","branch":"upstream"}}'
